# Generated by Django 5.0.2 on 2024-02-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
